##DockerFile generated by DeepSeek AI

# Use an official Node.js runtime as the base image
# Updated from 16 to 20 because of prisma
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma Client
RUN npx prisma generate

# Build the TypeScript project
RUN npm run build

# Expose the API port
EXPOSE 3000

# Command to run the application
#CMD ["npm", "start"]
CMD ["node", "dist/index.js"]